# Generated by Django 2.0 on 2018-08-08 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field',
            field=models.TextField(choices=[('N/A', 'N/A'), ('administration', 'Administration'), ('banking', 'Banking'), ('design', 'Design'), ('education', 'Education'), ('engineering', 'Engineering'), ('entrepreneur', 'Entrepreneur'), ('government', 'Government'), ('health', 'Health'), ('legal', 'Legal'), ('media', 'Media'), ('research', 'Research'), ('sales', 'Sales')], default='N/A'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2018, 8, 8)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='aboutMe',
            field=models.TextField(blank=True),
        ),
    ]
